class Jokes {
  static jokes = [
    'Two guys walked into a bar.\nThe third guy ducked.',
    'Why are elevator jokes so classic and good?\nThey work on many levels.',
    'What kind of drink can be bitter and sweet?\nReali-tea.',
    'What did Tennessee?\nThe same thing as Arkansas.',
    'Why did the man fall down the well?\nBecause he couldn’t see that well.',
    'When does a joke become a “dad joke?”\nWhen it becomes apparent.',
    'Which state has the most streets?\nRhode Island.',
    'I used to hate facial hair, but then it grew on me.',
    'Sundays are always a little sad, but the day before is a sadder day.',
    'You’re American when you go into a bathroom and when you come out, but what are you while you’re in the bathroom?\nEuropean.',
    'How does a penguin build his house?\nIgloos it together.',
    'What kind of music do chiropractors like?\nHip pop.',
    'I was going to tell a time-traveling joke, but you guys didn’t like it.',
    'When you have a bladder infection, urine trouble.',
    'What do you call a toothless bear?\nA gummy bear!',
    'Want to hear a joke about construction?\nI’m still working on it.',
    'Someone told me that I should write a book.\nI said, That’s a novel concept.',
    'Two goldfish are in a tank. One says to the other, Do you know how to drive this thing?',
    'I tell dad jokes, but I don’t have any kids.\nI’m a faux pa.',
    'I know a lot of jokes about retired people, but none of them work.',
    'Sore throats are a pain in the neck.',
    'What’s red and smells like blue paint?\nRed paint.',
    'What do you call an unpredictable camera?\nA loose Canon.',
    'What do sprinters eat before a race?\nNothing—they fast.',
    'Why couldn’t the bicycle stand up by itself?\nIt was two-tired.',
    'I’m so good at sleeping, I can do it with my eyes closed.',
    'Why shouldn’t you write with a broken pencil?\nBecause it’s pointless.',
    'Do mascara and lipstick ever argue?\nSure, but then they makeup.',
    'Why did two tall people get along so well?\nThe could really see eye to eye.',
    'What kind of bird is always getting hurt?\nThe owl.',
    'What did the dishwasher say to the oven after a productive day?\nYou’ve been on fire!',
    'What did one furniture maker say to another during a tense discussion?\nLet’s table this.',
    'Why was the ghost so tired?\nHe worked the graveyard shift.',
    'What kind of shape may have been knighted?\nCir-cles.',
    'What did the baker say when she won an award?\nIt was a piece of cake.',
    'What did the geometry teacher say when the class had trouble solving a problem?\nLet’s try a different angle.',
  ]
}
